### PR TITLE
add general unit test for methods and metrics config files

### PR DESCRIPTION
**Pull request by KaiWaldrant**
add general unit tests for methods and metrics to check certain fields are in the config file.

### CODE REVIEW

**Comment by rcannood** [comment]
I like this very much! :+1:

**Comment by rcannood** [comment]
@KaiWaldrant Can you check whether the errors are actual errors, or a problem with the unit tests?

**Comment by KaiWaldrant** [comment]
there was 1 error in the unit_test due to the change in of the `type`. The others are config errors from the components that er being exposed.

**Comment by KaiWaldrant** [comment]
the error that is remaining is the issue with the docker scib version I guess

**Review by rcannood — APPROVED** [review]

**Pull request merged**
