### PR TITLE
Migrate the Neurips 2021 predict modality task

### PR DESCRIPTION
**Pull request by KaiWaldrant**
This PR migrates the NeurIPS 2021 task from https://github.com/openproblems-bio/neurips2021_multimodal_viash/tree/main/src/predict_modality to this repo.

Note that this task still needs to be extended with the competitions top methods in https://github.com/openproblems-bio/neurips2021_multimodal_topmethods/tree/main/src/predict_modality/methods.

### CODE REVIEW

**Review by rcannood — APPROVED** [review]
LGTM. A few tests are failing outside this PR, but those should be tackled separately. @KaiWaldrant Can you review my changes?

**Comment by rcannood** [comment]
```
$ src/tasks/predict_modality/workflows/run/run_test.sh
N E X T F L O W  ~  version 23.04.2
Launching `src/tasks/predict_modality/workflows/run/main.nf` [elegant_brahmagupta] DSL2 - revision: 12b3e62960
executor >  local (10)
[9f/c2c5c3] process > run_wf:run_components_wf:meanpergene:meanpergene_process (pancreas.meanpergene)          [100%] 1 of 1, cached: 1 ✔
[d9/14acfc] process > run_wf:run_components_wf:random_predict:random_predict_process (pancreas.random_predict) [100%] 1 of 1, cached: 1 ✔
[58/9053e9] process > run_wf:run_components_wf:zeros:zeros_process (pancreas.zeros)                            [100%] 1 of 1, cached: 1 ✔
[fb/3be46e] process > run_wf:run_components_wf:solution:solution_process (pancreas.solution)                   [100%] 1 of 1, cached: 1 ✔
[76/2dd707] process > run_wf:run_components_wf:knnr_py:knnr_py_process (pancreas.knnr_py)                      [100%] 1 of 1, cached: 1 ✔
[ae/b10a58] process > run_wf:run_components_wf:knnr_r:knnr_r_process (pancreas.knnr_r)                         [100%] 1 of 1, cached: 1 ✔
[fd/289e1b] process > run_wf:run_components_wf:lm:lm_process (pancreas.lm)                                     [100%] 1 of 1, cached: 1 ✔
[9e/33cf96] process > run_wf:run_components_wf:newwave_knnr:newwave_knnr_process (pancreas.newwave_knnr)       [100%] 1 of 1, cached: 1 ✔
[76/dd4bdf] process > run_wf:run_components_wf:random_forest:random_forest_process (pancreas.random_forest)    [100%] 1 of 1, cached: 1 ✔
[bb/fdae7b] process > run_wf:run_components_wf:correlation:correlation_process (pancreas.newwave_knnr)         [100%] 9 of 9 ✔
[ff/ad1758] process > run_wf:run_components_wf:mse:mse_process (pancreas.zeros)                                [100%] 9 of 9, cached: 9 ✔
[31/96fda0] process > run_wf:extract_scores:extract_scores_process (output)                                    [100%] 1 of 1 ✔
```

:)

**Review by KaiWaldrant — COMMENTED** [review]
LGTM

**Comment by rcannood** [comment]
I extended the `run_test.sh` because some components run code conditionally on whether the dataset is atac or cite.

```
$ src/tasks/predict_modality/workflows/run/run_test.sh
N E X T F L O W  ~  version 23.04.2
Launching `src/tasks/predict_modality/workflows/run/main.nf` [extravagant_avogadro] DSL2 - revision: 12b3e62960
executor >  local (109)
[92/a7ad98] process > run_wf:run_components_wf:meanpergene:meanpergene_process (bmmc_multiome_starter.meanpergene)            [100%] 4 of 4 ✔
[79/5bc863] process > run_wf:run_components_wf:random_predict:random_predict_process (bmmc_multiome_starter.random_predict)   [100%] 4 of 4 ✔
[f5/e2c25a] process > run_wf:run_components_wf:zeros:zeros_process (bmmc_multiome_starter.zeros)                              [100%] 4 of 4 ✔
[e8/d245cf] process > run_wf:run_components_wf:solution:solution_process (bmmc_multiome_starter.solution)                     [100%] 4 of 4 ✔
[cc/4f2045] process > run_wf:run_components_wf:knnr_py:knnr_py_process (bmmc_multiome_starter_swapped.knnr_py)                [100%] 4 of 4 ✔
[85/c1bf2c] process > run_wf:run_components_wf:knnr_r:knnr_r_process (bmmc_cite_starter.knnr_r)                               [100%] 4 of 4 ✔
[9f/91d60d] process > run_wf:run_components_wf:lm:lm_process (bmmc_multiome_starter_swapped.lm)                               [100%] 4 of 4 ✔
[5b/dd7fb5] process > run_wf:run_components_wf:newwave_knnr:newwave_knnr_process (bmmc_multiome_starter_swapped.newwave_knnr) [100%] 4 of 4 ✔
[79/d18143] process > run_wf:run_components_wf:random_forest:random_forest_process (bmmc_cite_starter.random_forest)          [100%] 4 of 4 ✔
[f9/a8971e] process > run_wf:run_components_wf:correlation:correlation_process (bmmc_multiome_starter_swapped.lm)             [100%] 36 of 36 ✔
[e4/580d5b] process > run_wf:run_components_wf:mse:mse_process (bmmc_multiome_starter_swapped.lm)                             [100%] 36 of 36 ✔
[24/591632] process > run_wf:extract_scores:extract_scores_process (output)                                                   [100%] 1 of 1 ✔
Completed at: 14-Jul-2023 06:54:48
Duration    : 4m 41s
CPU hours   : 2.1
Succeeded   : 109
```

**Pull request merged**
