### PR TITLE
add several control methods for batch integration

### PR DESCRIPTION
**Pull request by KaiWaldrant**
## Describe your changes
add some of the control methods from v1.

## Checklist before requesting a review
- [x] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [x] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Bug fixes

- [x] Proposed changes are described in the CHANGELOG.md

- [x] CI Tests succeed and look good!

### CODE REVIEW

**Comment by rcannood** [comment]
What needs to be done for this PR?

**Comment by KaiWaldrant** [comment]
Add the control methods :)

**Comment by KaiWaldrant** [comment]
@rcannood The test_resources for batch integration need to be rebuild and uploaded

**Comment by rcannood** [comment]
> @rcannood The test_resources for batch integration need to be rebuild and uploaded. Unit test should work then

They were updated! :)

**Review by rcannood — APPROVED** [review]
LGTM! :relaxed: Thanks for your hard work!

**Pull request merged**
